name: nodered
description: NodeRED api in dart. Create edit and delete nodes, there is also option to install third party libraries
version: 1.0.2+1
repository: https://github.com/CyBear-Jinni/nodered
homepage: https://nodered.org/

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # Library for making HTTP requests.
  http: ^1.1.0
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^4.1.0
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.0.2+1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
